### ISSUE TITLE
🚀 Roadmap for V1

### ISSUE THREAD

**Issue by leonardomso** [leonardomso/podhouse#213]
### Summary

Here's a few features and issues that should be worked on in order to release the V1 of Podhouse.

#### Landing

- [x] Add Blog page for landing page.
- [x] Add Advertise page for showing how the user can advertise its own podcast on Podhouse.
- [x] Improve SEO for landing page to be the most optimized possible.
- [ ] Add newsletter input for capturing user emails and notify about new releases, recommendations, etc.

#### Web

- [ ] Set up husky and lint-staged (#288).
- [x] Set up Sentry for capturing errors (#287).
- [x] Set up environment variables for Web app (#289).
- [x] Add Tooltip component improve a11y (#179).
- [x] Create Forgot Password component (#295).
- [x] Create Reset Password component (#296).
- [x] Create Settings component (#297).
- [x] Create Password component for Settings (#305).
- [x] Create About component for Settings (#304). 
- [x] Create FAQ component for Settings (#306). 
- [x] Create Feedback component for Settings (#307). 
- [x] Create Privacy Policy component for Settings (#308). 
- [x] Create Terms component for Settings (#309). 
- [ ] Create Error Boundary component and make sure they're working (#290).
- [ ] Write tests for Podcast component (#291).
- [ ] Write tests for Episode component (#292).
- [ ] Write tests for Subscriptions component (#293).
- [ ] Write tests for Favorites component (#294).
- [ ] Display Play, Favorite and Icon on a podcast item (like Spotify does).
- [ ] Add forgot password and reset password workflow.
- [ ] Add dark mode.
- [ ] Add feature for user updating his own avatar.
- [ ] Add keyboard shortcuts.
- [ ] Add feature for displaying episodes on grid or cards.
- [ ] Add feature for creating shareable URL for podcast and episode.
- [ ] Add feature for changing order of episodes (newest or oldest).
- [ ] Add customized playback (like PocketCasts does).
- [ ] Add feature for sharing an episode from a specific part (like YouTube does).
- [ ] Add listening history (and clean history).
- [ ] Add favorites feature. 
- [ ] Add custom rate.
- [ ] Add custom volume.
- [ ] Add queue of episodes.
